### ISSUE TITLE
Full page reloading while selecting another device from drop down.

### ISSUE THREAD

**Issue by kamalkrbh** [STORDIS/orca_ui#21]
While selecting different device from dropdown in tabbed pane full page get reloaded. Instead only the tabbed pane should get reloaded.

**Comment by vivek-metricdust** [comment]
the cause of this issue is onChange={(e) => window.location.pathname = `/devices/${e.target.value}`} in the TabbedPane page we are reloading entire page instead of the specific route.

Solution is we can implement the route-based view of components where we can reload a specific route.



![Image](https://github.com/STORDIS/orca_ui/assets/157693017/05c4d13f-0ef4-4863-97f6-2eb4064082d9)

Here is a sample layout which we can use for implementation.
